// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pan_getLeadingBits (
        ap_ready,
        ip32Bit,
        i,
        ap_return
);


output   ap_ready;
input  [31:0] ip32Bit;
input  [4:0] i;
output  [127:0] ap_return;

wire   [4:0] xor_ln8_fu_26_p2;
wire   [31:0] zext_ln8_fu_32_p1;
wire   [31:0] prefix_fu_36_p2;
wire   [31:0] prefix_1_fu_42_p2;

assign ap_ready = 1'b1;

assign prefix_1_fu_42_p2 = prefix_fu_36_p2 << zext_ln8_fu_32_p1;

assign prefix_fu_36_p2 = ip32Bit >> zext_ln8_fu_32_p1;

assign xor_ln8_fu_26_p2 = (i ^ 5'd31);

assign zext_ln8_fu_32_p1 = xor_ln8_fu_26_p2;

assign ap_return = {{prefix_1_fu_42_p2}, {96'd0}};

endmodule //pan_getLeadingBits
